services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: task-management-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - task-management-network
    healthcheck:
      test: ["CMD-SHELL", "timeout 10 bash -c 'until echo > /dev/tcp/localhost/1433; do sleep 1; done' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-management-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TaskDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
    ports:
      - "5113:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - task-management-network
    volumes:
      - ./backend:/src
      - /src/bin
      - /src/obj

  # Frontend Application
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: task-management-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - task-management-network

volumes:
  sqlserver_data:
    driver: local

networks:
  task-management-network:
    driver: bridge 